"""
Email Generator Module (v4 - Improved Prompts)
Uses Claude Sonnet 4.6 for highest quality emails.
FIXES: Softer "hiring" language, JD-specific openers, more creative variation.
"""
import random
import logging
from anthropic import Anthropic
from config import (
    ANTHROPIC_API_KEY, EMAIL_GENERATOR_MODEL, EMAIL_TEMPERATURE,
    SENDER_NAME, SENDER_PHONE, SENDER_EMAIL
)

logger = logging.getLogger(__name__)
client = Anthropic(api_key=ANTHROPIC_API_KEY)

SUBJECT_LINES = {
    "standard": [
        "{job_title} at {company}",
        "{job_title} role at {company}",
        "{job_title} position at {company}",
    ],
    "conversational": [
        "Quick note about the {job_title} role",
        "Reaching out about {job_title}",
        "Interest in the {job_title} position",
    ],
    "team_focused": [
        "{job_title} opening on your team",
        "{job_title} role on the {department} team",
    ]
}

TRANSITION_LINES = [
    "Here's why I'd be a strong fit:",
    "A few reasons I think I'd be a good match:",
    "Here's what makes me a fit for this role:",
    "This is what I've been working on:",
    "Here's what I bring to the table:",
    "A quick look at my relevant experience:",
]

CTA_HIRING_MANAGER = [
    "Would love the opportunity to interview for this role.",
    "I'd welcome the chance to interview.",
    "Would be great to interview and discuss further.",
    "I'd appreciate the opportunity to interview.",
    "Would love to interview if you think there's a fit.",
]

CTA_RECRUITER = [
    "Would love to interview for this role, or if you could point me to the hiring manager, I'd appreciate it.",
    "I'd welcome the chance to interview. If there's a better contact for this role, happy to reach out to them as well.",
    "Would be great to interview, or if you could connect me with the hiring manager, that would be helpful.",
    "I'd appreciate the opportunity to interview. If there's someone else I should reach out to, please let me know.",
]

RESUME_OFFER = [
    "I've attached my resume for your review.",
    "My resume is attached if you'd like to take a closer look.",
    "I've included my resume for your reference.",
    "Resume attached for your review.",
    "I've attached my resume in case it's helpful.",
]

FOLLOW_UP_1_TEMPLATE = """Hi {first_name},

Just bumping this up. I know things get buried. Still interested in the {job_title} role.

Would love to chat if you have a few minutes.

Thanks,
Saurabh"""

FOLLOW_UP_2_TEMPLATE = """Hi {first_name},

Last note from me. Totally understand if timing isn't right.

If anything changes, I'm at {email}.

Thanks,
Saurabh"""

# Resume points are now dynamically generated by Claude based on JD + full experience


class VariationTracker:
    def __init__(self):
        self.used_subjects = []
        self.used_transitions = []
        self.used_ctas = []
        self.used_resume_offers = []

    def get_subject(self, job_title, company, department="Data"):
        all_subjects = []
        for pool in SUBJECT_LINES.values():
            for t in pool:
                f = t.format(job_title=job_title, company=company, department=department)
                if f not in self.used_subjects:
                    all_subjects.append(f)
        if not all_subjects:
            self.used_subjects = []
            return self.get_subject(job_title, company, department)
        choice = random.choice(all_subjects)
        self.used_subjects.append(choice)
        return choice

    def get_transition(self):
        available = [t for t in TRANSITION_LINES if t not in self.used_transitions]
        if not available:
            self.used_transitions = []
            available = TRANSITION_LINES
        choice = random.choice(available)
        self.used_transitions.append(choice)
        return choice

    def get_cta(self, contact_type):
        pool = CTA_RECRUITER if contact_type == "recruiter" else CTA_HIRING_MANAGER
        available = [c for c in pool if c not in self.used_ctas]
        if not available:
            self.used_ctas = []
            available = pool
        choice = random.choice(available)
        self.used_ctas.append(choice)
        return choice

    def get_resume_offer(self):
        available = [r for r in RESUME_OFFER if r not in self.used_resume_offers]
        if not available:
            self.used_resume_offers = []
            available = RESUME_OFFER
        choice = random.choice(available)
        self.used_resume_offers.append(choice)
        return choice


def generate_emails(contacts, jd_text, company, job_title, location,
                    sector, company_size, name_drop=None):
    tracker = VariationTracker()
    emails = []
    for i, contact in enumerate(contacts):
        subject = tracker.get_subject(job_title, company)
        transition = tracker.get_transition()
        cta = tracker.get_cta(contact.contact_type)
        resume_offer = tracker.get_resume_offer()
        email_body = _generate_single_email(
            contact=contact, jd_text=jd_text, company=company,
            job_title=job_title, location=location, sector=sector,
            company_size=company_size,
            name_drop=name_drop if i == 0 else None,
            transition=transition, cta=cta,
            resume_offer=resume_offer
        )
        emails.append({
            "contact_name": contact.name, "contact_title": contact.title,
            "contact_type": contact.contact_type,
            "subject": subject, "body": email_body
        })
    return emails


def generate_follow_up(contact_name, job_title, follow_up_number):
    first_name = contact_name.split()[0] if contact_name else "there"
    if follow_up_number == 1:
        body = FOLLOW_UP_1_TEMPLATE.format(first_name=first_name, job_title=job_title)
    else:
        body = FOLLOW_UP_2_TEMPLATE.format(first_name=first_name, email=SENDER_EMAIL)
    return {"subject": f"Re: {job_title}", "body": body}






def _generate_single_email(contact, jd_text, company, job_title, location,
                           sector, company_size, name_drop, transition,
                           cta, resume_offer):
    first_name = contact.name.split()[0] if contact.name else "there"

    # IMPROVED OPENER INSTRUCTIONS
    if contact.contact_type == "recruiter":
        opener_instruction = (
            "Use a RECRUITER opener with SOFT/UNCERTAIN language. "
            "NEVER say 'saw you are hiring' or 'you're hiring'. Instead use phrases like: "
            "'I came across a {job_title} position that might be on your radar' or "
            "'I noticed a {job_title} opening that could be related to your team' or "
            "'I saw a {job_title} role at {company} and thought you might be involved in the search'. "
        )
        if name_drop:
            opener_instruction += f"You can mention {name_drop.name} ({name_drop.title}) with uncertain language like 'could be on their team'."
    elif name_drop:
        opener_instruction = (
            f"Use a NAME-DROP opener referencing {name_drop.name} ({name_drop.title}). "
            f"NEVER say 'saw you are hiring'. Instead say something like: "
            f"'I noticed {name_drop.name} on the [team] team and came across a {job_title} opening "
            f"that could be on your team.' Use 'could be' or 'might be', never definitive."
        )
    else:
        opener_instruction = (
            f"Use a DIRECT/CONFIDENT opener. NEVER say 'saw you are hiring'. Instead: "
            f"Start with what YOU do that's directly relevant to the JD. Example: "
            f"'I'm a data scientist who builds [SPECIFIC THING FROM JD, not generic]. "
            f"Came across the {job_title} role at {company} and it aligns with exactly what I've been doing.' "
            f"The first sentence MUST reference a specific skill or system from the JD, not generic 'data pipelines'."
        )

    system_prompt = f"""You are writing a cold outreach email for Saurabh Vyawahare, a Data Scientist with 4+ years of experience.

HOW TO WRITE THE NUMBERED POINTS (THIS IS THE MOST IMPORTANT PART):

Step 1: Read the JD below. Identify the 2-3 most critical things the employer is looking for.
Step 2: For each of those JD requirements, write a point that says "I built/designed/created [exactly what the JD asks for]."
Step 3: Use Saurabh's experience below ONLY as proof that he can credibly claim these things. Do NOT pick random resume bullets.

THE POINTS MUST MIRROR THE JD. If the JD says:
- "Build forecasting models for retail demand" → Write: "I built demand forecasting models using [relevant technique] to predict [business outcome]"
- "A/B testing for marketing campaigns" → Write: "I designed A/B testing pipelines to measure campaign impact on conversion and engagement"  
- "SQL and Python for data pipelines" → Write: "I built automated data pipelines in Python and SQL to process and validate large-scale datasets"
- "Dashboard reporting for stakeholders" → Write: "I created dashboards translating complex analytics into actionable insights for business stakeholders"

The reader should think: "This person has done EXACTLY what we need." Every point should feel like it was written FOR this specific job.

SAURABH'S EXPERIENCE (REFERENCE ONLY, to ensure claims are credible):
- Survival analysis, XGBoost, LightGBM, logistic regression for predictive models
- Customer segmentation using k-means clustering on 1M+ records
- Churn prediction, retention analytics, customer lifetime value modeling
- A/B testing pipelines for pricing, promotions, campaign measurement
- Multi-touch attribution for marketing channel ROI
- Recommendation engines using collaborative filtering
- ETL/SQL pipelines, Snowflake, MongoDB, data migration
- Power BI and Tableau dashboards for stakeholder reporting
- NLP, vector search, RAG systems, OpenAI API integration
- Real-time ML monitoring (drift detection, latency, accuracy)
- Healthcare claims analysis, risk scoring, MedDRA mapping, compliance

CRITICAL RULES:
- NEVER say "saw you are hiring" or "you're hiring for". Use softer language.
- The opener MUST reference something SPECIFIC from the JD, not generic.
- NO "I hope this finds you well"
- NO percentages or metrics in numbered points
- NO company names in numbered points
- NO dashes anywhere (use commas and periods only)
- Start each numbered point with "I built" or "I designed" or "I created"
- Keep concise and confident, not needy

STRUCTURE (follow exactly):
1. "Hi {first_name},"
2. Opener (1-2 sentences, reference specific JD detail)
3. Genuine reason (1 sentence about why this company/role)
4. Transition line (use exactly as provided)
5. Numbered points (2-3 points derived FROM THE JD, phrased as what you've done)
6. CTA (use exactly as provided)
7. Resume offer (use exactly as provided)
8. "Thanks,\\nSaurabh Vyawahare\\n857-230-7888"

Return ONLY the email body. No subject line. No explanations."""

    user_prompt = f"""RECIPIENT: {contact.name}, {contact.title} at {company}
TYPE: {contact.contact_type}
JOB: {job_title} at {company} ({location})
SECTOR: {sector} | SIZE: {company_size}

OPENER: {opener_instruction}
TRANSITION (use exactly): {transition}
CTA (use exactly): {cta}
RESUME OFFER (use exactly): {resume_offer}

FULL JD (read this FIRST, your numbered points come FROM here):
{jd_text[:2500]}

INSTRUCTIONS: Read the JD above. What are the 2-3 most important things this employer wants? Write your numbered points about THOSE things. Say "I built" or "I designed" for each. The reader should feel like you wrote this email specifically for their job, not a generic template."""

    try:
        response = client.messages.create(
            model=EMAIL_GENERATOR_MODEL,
            max_tokens=800,
            temperature=EMAIL_TEMPERATURE,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}]
        )
        email_body = response.content[0].text.strip()
        email_body = email_body.replace(" — ", ", ").replace(" – ", ", ").replace("—", ",").replace("–", ",")
        if "Saurabh Vyawahare" not in email_body:
            email_body += f"\n\nThanks,\nSaurabh Vyawahare\n857-230-7888"
        return email_body

    except Exception as e:
        logger.error(f"Email generation failed: {e}")
        return _build_fallback_email(first_name, contact.contact_type, job_title, company,
                                     name_drop, transition, cta, resume_offer)


def _build_fallback_email(first_name, contact_type, job_title, company,
                          name_drop, transition, cta, resume_offer):
    if name_drop and contact_type != "recruiter":
        opener = f"I noticed {name_drop.name} on the team and came across a {job_title} opening that could be on your team."
    elif contact_type == "recruiter":
        opener = f"I came across a {job_title} position at {company} that might be on your radar. The focus on data and analytics is exactly what I've been doing."
    else:
        opener = f"I'm a data scientist with 4+ years of experience building production data systems. Came across the {job_title} role at {company} and it aligns with exactly what I've been doing."

    return f"""Hi {first_name},

{opener}

The work your team is doing at {company} is exactly the kind of problem I want to solve.

{transition}

1. I built predictive models and data pipelines tailored to business-specific outcomes
2. I created dashboards and analytics systems that translate complex data into actionable insights for stakeholders

{cta}

{resume_offer}

Thanks,
Saurabh Vyawahare
857-230-7888"""
